services:
  web:
    build: .
    container_name: crossword-app
    volumes:
      - staticfiles:/app/staticfiles
    restart: unless-stopped
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: crossword-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - staticfiles:/staticfiles:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - default
      - edge

networks:
  edge:
    external: true

volumes:
  staticfiles:
